In [11]:
## learn about numpy 

In [12]:
import numpy as np

In [13]:
a= [1, 2, 45, 12, 34]
print(a)
type(a)

[1, 2, 45, 12, 34]


list

In [14]:
npp= np.array(a)
type(npp)

numpy.ndarray

In [15]:
myList= [[2,434, 434], [3, 43, 54], [343, 45, 13]]
print(myList)

[[2, 434, 434], [3, 43, 54], [343, 45, 13]]


In [16]:
np.array(myList)

array([[  2, 434, 434],
       [  3,  43,  54],
       [343,  45,  13]])

In [17]:
#create numpy array
#arange([start,] stop[, step,], dtype=None, *, like=None)
arr= np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [18]:
type(arr)

numpy.ndarray

In [19]:
#zeros(shape, dtype=float, order='C', *, like=None)
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#linspace(start,stop, num=50) num means how many number would you want between start and stop
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
#give two random number between 0 to 1
np.random.rand(1, 3)

array([[0.91874701, 0.90071485, 0.03342143]])

In [24]:
#give a random number list negetive and positive both
np.random.randn(2, 6)

array([[ 0.75314283, -1.53472134,  0.00512708, -0.12022767, -0.80698188,
         2.87181939],
       [-0.59782292,  0.47245699,  1.09595612, -1.2151688 ,  1.34235637,
        -0.12214979]])

In [25]:
#give random number(start, stop, size)
np.random.randint(0, 20, size=[2,3])

array([[ 1,  4,  0],
       [ 4,  1, 11]])

In [26]:
#when we need to same size randon value then we use seed method
np.random.seed(12)
np.random.randint(0, 10, 5)

array([6, 1, 2, 3, 3])

In [27]:
np.random.seed(12)
np.random.randint(0, 10, 6)

array([6, 1, 2, 3, 3, 0])

In [28]:
arr= np.random.randint(0, 100, 10)
arr

array([22, 49, 52,  5, 13, 89, 34, 75, 74,  0])

In [29]:
arr.max()

89

In [30]:
arr.argmin()

9

In [31]:
arr.argmax()

5

In [32]:
arr

array([22, 49, 52,  5, 13, 89, 34, 75, 74,  0])

In [33]:
arr.reshape(2,5)

array([[22, 49, 52,  5, 13],
       [89, 34, 75, 74,  0]])

In [34]:
arr= np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [36]:
arr[5:]

array([5, 6, 7, 8, 9])

In [37]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
new_arr= arr[:]
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
new_arr[:4]= 100
new_arr[:]
print(arr)

[100 100 100 100   4   5   6   7   8   9]


In [40]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [41]:
new_arr= arr
new_arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [42]:
arr_2d= np.arange(0, 50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [43]:
arr_2d[0,1]

1

In [44]:
#row 1 to second row -1, coloum 3 to 5-1
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [45]:
arr_2d[1:4, 3:5]

array([[13, 14],
       [23, 24],
       [33, 34]])

In [46]:
arr_2d[1:2, 2:4]

array([[12, 13]])

In [47]:
arr_2d[2:, 4:8]

array([[24, 25, 26, 27],
       [34, 35, 36, 37],
       [44, 45, 46, 47]])

In [48]:
arr= np.arange(0, 11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
bool_arr= arr>5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [51]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [52]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [53]:
##numpy basic mathmatical operation

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [56]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [58]:
#0/0 gives error so it gives nan 
arr/arr

C:\Users\Laptop\AppData\Local\Temp\ipykernel_7224\183249584.py:2: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [59]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [60]:
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [61]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])